### ISSUE TITLE
Steam4NET2 no longer working since Steam latest update

### ISSUE THREAD

**Issue by omega32** [SteamRE/open-steamworks#11]
I'm currently using the `Steam4NET2` library... but since the last Steam update, it's no longer working.

I can't create the `IClientEngine` interface.
The following code used to work, but now `ClientEngine` is `null`:

```
if (!Steamworks.Load())
    throw new SteamException("Unable to load steamclient library.");

IClientEngine ClientEngine;
try
{
    ClientEngine = Steamworks.CreateInterface<IClientEngine>();
}
catch (Exception ex)
{
    throw new SteamException("Unable to get IClientEngine interface.", ex);
}

if (ClientEngine == null)
    throw new SteamException("Unable to get IClientEngine interface.");
```

This code now throws the **"Unable to get IClientEngine interface"** exception. It was working before the latest Steam update.

Any ideas? Do we need to update `IClientEngine` to match the one in the Steam client?
Any help would be appreciated. Thanks.

**Comment by josh33901** [comment]
i can confirm broken for opensteamworks aswell

**Comment by omega32** [comment]
Great. It's working again. Thanks @Netshroud !
