### ISSUE TITLE
Test Platform crash

### ISSUE THREAD

**Issue by LittleKu** [SteamRE/open-steamworks#13]
When I run the Test Platform program and it crash on 
friendID = pClientFriends->GetFriendByIndex(i, k_EFriendFlagImmediate);
and the error message 
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.
what happen ?

**Comment by Netshroud** [comment]
The very latest code is only compatible with the Steam Client Beta. Have you opted into the beta?

**Comment by LittleKu** [comment]
Not

**Comment by LittleKu** [comment]
So where I can clone the release code ?

**Comment by Netshroud** [comment]
Try running from 41773f7.

Otherwise, just opt into the beta.

**Comment by LittleKu** [comment]
I just $ git reset --hard 41773f78d62bdfdab28e24fe68b6564f4a464d77
and now I can't get the client engine address, pClientEngine is NULL.

**Comment by LittleKu** [comment]
I change #define CLIENTENGINE_INTERFACE_VERSION "CLIENTENGINE_INTERFACE_VERSION003" to #define CLIENTENGINE_INTERFACE_VERSION "CLIENTENGINE_INTERFACE_VERSION004"
the same as the lastest source

**Comment by Netshroud** [comment]
And it works for you now?

**Comment by LittleKu** [comment]
Not

**Comment by Netshroud** [comment]
41773f7 with IClientEngine v4 doesn't work?

Can you either provide more info, or switch to client beta?

**Comment by LittleKu** [comment]
I want to make a Thirdpart tools with steam, so I need the release version, because you can't ask the others switch to beta version, and Now I just use this code and vs 2013 and steam, that is all. I just open the solution file with vs2013 and then compile the Test Platform and debug it. when I try to get the friend's info, it crash.

**Comment by Netshroud** [comment]
You can't rely on IClientAnything for software you ship to other users. There's no guarantee of compatibilit; it can and will break your program at Valve's whim.

**Comment by LittleKu** [comment]
When I switch to the beta version, the last version code work, the issue will be closed !
