### ISSUE TITLE
Identifier TSteamGlobalUserID undefined if NO_STEAM defined

### ISSUE THREAD

**Issue by win32re** [SteamRE/open-steamworks#15]

**Comment by win32re** [comment]
This is how I'm including Steamworks:

```
#define NO_STEAM
#include <osw/Steamworks.h>
```

**Comment by VoiDeD** [comment]
I believe that this, along with #14 is intentional.

The `NO_STEAM` define is meant to exclude code that's relevant to the older Steam.dll library that handled the legacy Steam2 protocol that is no longer in use. `TSteamGlobalUserID` is also a Steam2 structure that is no longer used.

**Comment by Netshroud** [comment]
That's my understanding as well.

Why are you defining `NO_STEAM`? What were you expecting it would do?

**Comment by win32re** [comment]
I expected it to reduce the amount of included headers, my bad :smile:

Solved!
