### ISSUE TITLE
about the docment of this project

### ISSUE THREAD

**Issue by LittleKu** [SteamRE/open-steamworks#16]
never mind, may be this is not a issues.
I found that some classes name ISteam2Bridge002/ISteam2Bridge001, and there is a member function  is "CreateProcess", so my problem is does the function create a game process with steam ?
if so, how can I use it ?
Thx advance :)

**Comment by Netshroud** [comment]
The purpose of each function is either documented by Steamworks, undocumented with some understandable purpose, or reverse-engineered and completely unknown. I don't know what purpose `ISteam2Bridge` serves anymore, as Steam2 is just about entirely dead at this point.

> never mind, may be this is not a issues.

Closing, not minding. :)
