### ISSUE TITLE
'System.AccessViolationException - Can't publish to workshop from application

### ISSUE THREAD

**Issue by yangladesh** [SteamRE/open-steamworks#19]
I am having trouble getting passed an issue that prevents a .vpk file to be published to the game's workshop. A team member has actually gotten it to publish twice, but I have not, and since then, he has not been able to either. We are using Steam4NET.dll. When I hit publish, it seems to be going ok through the code, but once it hits PublishWorkshopFile(), it throws the following error:

An unhandled exception of type 'System.AccessViolationException' occurred in Steam4NET.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

When using the other Steam4NET (not Steam4NET2), it worked before the June update on Steam, when it started throwing "Failed to init Steam client engine." This one gets passed that error, but has the 'System.AccessViolationException' error.

Fix either of these issues of the separate Steam4NET libraries, I just need publishing workshop to work.

**Comment by azuisleet** [comment]
I re-synced Steam4NET (the top level project on SteamRE), and I'm not having any issues with Workshop. Take a look at this example and let me know:

https://gist.github.com/azuisleet/db57a3c7e5ca85b9ffdf

**Comment by yangladesh** [comment]
I get this:
An unhandled exception of type 'System.AccessViolationException' occurred in Steam4NET.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

At:
[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt64 NativePublishWorkshopFileSSUSSESE( IntPtr thisptr, string pchFile, string pchPreviewFile, UInt32 nConsumerAppId, string pchTitle, string pchDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags, EWorkshopFileType eWorkshopFileType );
public UInt64 PublishWorkshopFile( string pchFile, string pchPreviewFile, UInt32 nConsumerAppId, string pchTitle, string pchDescription, ERemoteStoragePublishedFileVisibility eVisibility, ref SteamParamStringArray_t pTags, EWorkshopFileType eWorkshopFileType ) 
{
return this.GetFunction( this.Functions.PublishWorkshopFile27 )( this.ObjectAddress, pchFile, pchPreviewFile, nConsumerAppId, pchTitle, pchDescription, eVisibility, ref pTags, eWorkshopFileType ); 
}



And I am using Steam4NET2'S version. The one you are talking about hasn't worked for us since June. It failed on init Steam Client or init Steam Client Engine.

**Comment by azuisleet** [comment]
It's likely related to the use of `ref SteamParamStringArray_t`. I don't believe Steam4NET2 is maintained, so I recommend you switch to the newer Steam4NET or you can fix up the signature by changing the `ref SteamParamStringArray_t` to `IntPtr` and manage the memory manually.
