### ISSUE TITLE
ReplyToFriendMessage wide characters

### ISSUE THREAD

**Issue by Salads** [SteamRE/open-steamworks#22]
I can't seem to send people utf8 encoded messages, since the parameter is a const char*

Is there a way to do this with a workaround, or could there be an overloaded function with a wide string?

**Comment by Netshroud** [comment]
I believe that `const char *` in this case is a pointer to an array of bytes, not a pointer to an array of ASCII characters. UTF-8 should work, I think Steam uses it internally for international characters etc.

**Comment by Salads** [comment]
Got it, thanks!
