### ISSUE TITLE
Test Platform "Run-Time Check Failure #0"

### ISSUE THREAD

**Issue by 5pHiNxX** [SteamRE/open-steamworks#24]
Hi, when i try to rund the Test Platform it crashes on
**pClientFriends->SendMsgToFriend(friendID, k_EChatEntryTypeChatMsg, cszMessage, strlen(cszMessage));**
with the error message:
**Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call. This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.**

I have opted into Steam Client Beta and the problem is still there. I also tried to use Revision 41773f7 but it didn't work either.

Thanks for your help.

**Comment by asherkin** [comment]
The IClient* interfaces are unversioned and unsafe - the Test Platform exists as general code example and for development of OSW itself, it is not a starting point for your own stuff.
