### ISSUE TITLE
Chat Logger no longer appears to work..

### ISSUE THREAD

**Issue by Acecool** [SteamRE/open-steamworks#25]
I've tried all combinations of launching Steam first, or the logger first.. I've tried elevated permissions on one, the other and both with the sequence of launching..

It no longer connects to steam and logs no longer get saved.

..strike this.. It no longer works with Steam Beta; non beta it works but it may not for much longer depending how quickly they roll out the updates.

**Comment by Luckz** [comment]
Did you try launching Steam, waiting for all the loading and spamming (notifications about friend requests, loading of avatars for people and groups) to finish, and then starting it?

**Comment by Acecool** [comment]
It seems to work perfectly on Windows 10 regardless of if it is launched before or after Steam...

It may have been an issue I was having with .NET ( if this uses .NET ) where the install was completely messed up on 7 and none of the fix / clean tools would repair the install and manually deleting the files didn't work, and manually going in and hunting down all the registry data for .net didn't work either ( may have missed a few ).. Anyway, clean install of 10 pro and it works fine now. 

Now that it is working, I'll close this ( feel free to re-open if you believe this should be looked into further; going to double check this as well to see if it uses .NET, and if so I may end up making a .NET wipe tool that removes everything and then reinstalls everything )...

I may change a few things or contribute now that it is working:

- to  help with file-naming; ie I'm now using SteamID3 to prevent getting a ton of files created when users change their name, but it'd be nice to use a profile-name or the static url name or something else such as checking aliases before creating a new file.

- A way to MERGE or SPLIT files would be great..

-  Additionally, there is an issue on 10 where hovering over the tray icon doesn't show connected / not connected after a while..

- And the most annoying ( I thought it was a dropbox issue but it isn't ) the file, when saved by Steam Chat Logger, doesn't update the file-modified timestamp until hours later or something... Makes it difficult when trying to find the exact file you want when it was the last message you received...

**Comment by Luckz** [comment]
"I'm now using SteamID3 to prevent getting a ton of files created when users change their name"
I use hardlinks named after the actual people in another folder. http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html makes this relatively easy.

"Additionally, there is an issue on 10 where hovering over the tray icon doesn't show connected / not connected after a while.."
if I hover and it shows nothing, that means it works, AFAIK. this is not win10-related.

" doesn't update the file-modified timestamp until hours later or something..."
The file is updated (I assume actually write access is closed) when you close the chat.

**Comment by Acecool** [comment]
That's what I was thinking, but the timestamp should still update on-save...]

I do use Symbolic links for AutoHotkey so everything can remain in my Dropbox / cloud folder and on a new-pc I run a setup.bat file which installs all of the software I use ( such as ahk plus symlink for library file and autohotkey.ahk in documents [ reads the location from registry so it supports other languages ] so I don't need to create a shortcut on each pc, plus anti-virus, and other utilities such as restart on crash, autosizer, etc... ) so moving between pcs is super easy..

I have been expanding on this over time; but creating a hard-link or symbolic-link for each file seems a tad much... but it is a fantastic idea to utilize... I may simply modify the code to allow a bat file to execute when it creates or edits a file so a symbolic or hard link can be made in a different directory ( or the same ) with a different name so the chat-log can always be steamid3 and the links can be user-friendly names ( the current name they use, or a nickname you have given them, or other options )... Even better would be to have an index file so if a user changes their name, the link gets renamed too ( if enabled; otherwise 1 per id or many per id depending on options )...

On Windows 7 I don't recall it ever not displaying something on hover but I may be mistaken. I do know that with 7 it would rarely connect to Steam but on 10 it is quite reliable but there have been cases where it didn't connect and I didn't notice until it was too late... Restarting Steam or chat logger seems to fix it ( so that could be another feature; restart chat logger every 15-30 seconds if no connection made, or simply improve upon the detection method so it doesn't get stuck not working; if it relies on a service, if Steam is running but the service isn't then start it... etc.. )


Cheers for the idea on using hard / symbolic links. ( although typical shortcuts could work too; but an automatic method of creating them via the logger app would be the best method in my opinion )

**Comment by Question2** [comment]
@acecool : Is there any chance you can provide a download link for chat logger, as you appear to have the application installed and running on your machine? The github repository has no download links.

**Comment by Acecool** [comment]
There used to be a "Releases" link which had the logger available for download... It may have been on bitbucket which is now deleted...

Pretty sure I mentioned it but the logger appears to work fine on Windows 10 x64 Pro ( The issues on 7 was likely due to a hosed .NET install which became that way from years of running the os and updates; no tool or manually removing files and registry settings seemed to work to fix that ).. Sometimes you will need to restart steam or the logger for it to say Connected to Steam...

I have been wanting to alter the code a bit to fix a few of the issues but health problems have prevented me being able to do much.

https://dl.dropboxusercontent.com/u/26074909/downloads/Chat%20Logger%2B%2B.zip
which should be the same as: https://dl.dropboxusercontent.com/u/26074909/tutoring/___welcome_docs/Acecool%20Utilities/_Installers/Chat%20Logger%201.2.rar

Other useful programs and the settings I use for the logger ( I have changed them because of the issue of people changing their names so frequently to now only use SteamID3 ): https://dl.dropboxusercontent.com/u/26074909/tutoring/___welcome_docs/_welcome_useful_programs_and_notepadpp_upgrades.lua.html
