### ISSUE TITLE
OpenSteamworks: wallet balance

### ISSUE THREAD

**Issue by iOn-cpp** [SteamRE/open-steamworks#29]
I cannot get user wallet balance.
It looks like some of IClientUser interface methods is not supported more.

**Comment by m4dEngi** [comment]
Just a little bit outdated... IClient interfaces tend to change with every client update. 
https://github.com/SteamRE/open-steamworks/pull/28/files#diff-2ad61cc5f09fbbaef95cc3579aa626a2

**Comment by iOn-cpp** [comment]
So how i can get wallet info? Or at the current time there is no way to do this?
Thanks.

**Comment by m4dEngi** [comment]
Replace original opensteamworks IClientUser.h with this one https://gist.github.com/m4dEngi/a2066c17f5b1895532fca68108e3387d 

Then you'll be able to get your wallet balance doing something like https://gist.github.com/m4dEngi/050fd9c92e4b0eb534cdecc0216e2486

... and keep in mind that i'm a pretty bad coder and might be doing something really wrong here even if it somehow works.
Also keep in mind that there's a great chance that after next client update this piece of code might stop working as expected.
