### ISSUE TITLE
No download link for chatlogger++

### ISSUE THREAD

**Issue by Question2** [SteamRE/open-steamworks#32]
Why is there no download link for the project? Who is in charge of this? The original website (open steamworks) just re-directs to github. No mention is made of who is in charge of chatlogger++ now or who the original developer was.

@asherkin @azuisleet @netshroud @psychonic @stgn @VoiDeD, you guys are listed as the organisation staff for "SteamRE", can you please clarify who is in charge of this?

Edit : Your website (http://opensteamworks.org/) also appear sto be offline.

**Comment by asherkin** [comment]
OSW is all but abandoned as Valve now make the SWSDK available publicly (albeit under restrictive license terms). 

Everything in Projects/ was contributed for use as sample code, we do not provide builds or support for it. 

The original developer of ChatLogger++ is credited at the top of every single source file. It is long abandoned. You are entirely on your own, as you'll see from other issues that have been filed against this repo there are numerous barriers to overcome building it today.

**Comment by Question2** [comment]
@Didrole : You are listed as the author of chatlogger, is there any chance you can provide a download link for the application?
