### ISSUE TITLE
Documentation for linux builds

### ISSUE THREAD

**Issue by talexand** [SteamRE/open-steamworks#8]
Is there any documentation for building any of these projects on Linux, or at least a current compatibility list?

**Comment by Netshroud** [comment]
Define 'building', and 'any of these projects'.

Open Steamworks is largely just a collection of headers to be imported, there's no building involved per se.

**Comment by talexand** [comment]
Sorry. For example, if I wanted to get Chat Logger++ working under Linux, how would I go about it?

**Comment by Netshroud** [comment]
You'd have to port it, it's currently Windows-only.
